INFO:root:Contract //root/smartbugs/dataset/int_bugs_9/0604/repair_tru/BCDN_repair_mutation_for_inttruncate_173_0.sol:blockcdn:
INFO:symExec:Running, please wait...
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 418, in propagate_taint
    if arithmetic_error["instruction"].data_in[0] == 32 or arithmetic_error["instruction"].data_in[0] == 31:
  File "/root/osiris/z3/z3.py", line 302, in __nonzero__
    return self.__bool__()
  File "/root/osiris/z3/z3.py", line 310, in __bool__
    return self.arg(0).eq(self.arg(1))
  File "/root/osiris/z3/z3.py", line 921, in arg
    _z3_assert(idx < self.num_args(), "Invalid argument index")
  File "/root/osiris/z3/z3.py", line 900, in num_args
    _z3_assert(is_app(self), "Z3 application expected")
  File "/root/osiris/z3/z3.py", line 1077, in is_app
    k = _ast_kind(a.ctx, a)
  File "/root/osiris/z3/z3.py", line 419, in _ast_kind
    return Z3_get_ast_kind(ctx.ref(), a)
  File "/root/osiris/z3/z3core.py", line 2581, in Z3_get_ast_kind
    r = _elems.f(a0, a1)
ArgumentError: argument 2: <type 'exceptions.Exception'>: timeout
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 65.9%
INFO:symExec:	  Arithmetic bugs: 	 True
INFO:symExec:	  └> Overflow bugs: 	 True
//root/smartbugs/dataset/int_bugs_9/0604/repair_tru/BCDN_repair_mutation_for_inttruncate_173_0.sol:blockcdn:173:1
totalSupply +=uint128(halfValue)
^
INFO:symExec:	  └> Underflow bugs: 	 False
INFO:symExec:	  └> Division bugs: 	 False
INFO:symExec:	  └> Modulo bugs:   	 False
INFO:symExec:	  └> Truncation bugs: 	 False
INFO:symExec:	  └> Signedness bugs: 	 False
INFO:symExec:	  Callstack bug: 	 False
INFO:symExec:	  Concurrency bug: 	 True
Flow 1:
//root/smartbugs/dataset/int_bugs_9/0604/repair_tru/BCDN_repair_mutation_for_inttruncate_173_0.sol:blockcdn:111:13
msg.sender.send(value)
^
Flow 2:
//root/smartbugs/dataset/int_bugs_9/0604/repair_tru/BCDN_repair_mutation_for_inttruncate_173_0.sol:blockcdn:196:13
msg.sender.send(value)
^
INFO:symExec:	  Time dependency bug: 	 True
//root/smartbugs/dataset/int_bugs_9/0604/repair_tru/BCDN_repair_mutation_for_inttruncate_173_0.sol:blockcdn:106:9
if(now <= closeTime) throw
^
//root/smartbugs/dataset/int_bugs_9/0604/repair_tru/BCDN_repair_mutation_for_inttruncate_173_0.sol:blockcdn:192:9
if(now <= closeTime ) throw
^
INFO:symExec:	  Reentrancy bug: 	 False
INFO:symExec:	 --- 50.0849089622 seconds ---
INFO:symExec:	====== Analysis Completed ======

  .oooooo.             o8o            o8o          
 d8P'  `Y8b            `"'            `"'          
888      888  .oooo.o oooo  oooo d8b oooo   .oooo.o
888      888 d88(  "8 `888  `888""8P `888  d88(  "8
888      888 `"Y88b.   888   888      888  `"Y88b. 
`88b    d88' o.  )88b  888   888      888  o.  )88b
 `Y8bood8P'  8""888P' o888o d888b    o888o 8""888P'


!!! SYMBOLIC EXECUTION TIMEOUT !!!
Unexpected error: <class 'ctypes.ArgumentError'>