INFO:root:Contract //root/smartbugs/dataset/int_bugs_9/0604/repair_cha/PYLNT_repair_mutation_for_greater_line_197.sol:PylonToken:
INFO:symExec:Running, please wait...

  .oooooo.             o8o            o8o          
 d8P'  `Y8b            `"'            `"'          
888      888  .oooo.o oooo  oooo d8b oooo   .oooo.o
888      888 d88(  "8 `888  `888""8P `888  d88(  "8
888      888 `"Y88b.   888   888      888  `"Y88b. 
`88b    d88' o.  )88b  888   888      888  o.  )88b
 `Y8bood8P'  8""888P' o888o d888b    o888o 8""888P'


!!! SYMBOLIC EXECUTION TIMEOUT !!!
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/root/osiris/z3/z3.py", line 137, in z3_error_handler
    def z3_error_handler(c, e):
  File "/root/osiris/symExec.py", line 2868, in handler
    raise Exception("timeout")
Exception: timeout
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 41.0%
INFO:symExec:	  Arithmetic bugs: 	 True
INFO:symExec:	  └> Overflow bugs: 	 False
INFO:symExec:	  └> Underflow bugs: 	 True
//root/smartbugs/dataset/int_bugs_9/0604/repair_cha/PYLNT_repair_mutation_for_greater_line_197.sol:PylonToken:198:9
balanceOf[_from] -= _value
^
INFO:symExec:	  └> Division bugs: 	 False
INFO:symExec:	  └> Modulo bugs:   	 False
INFO:symExec:	  └> Truncation bugs: 	 False
INFO:symExec:	  └> Signedness bugs: 	 False
INFO:symExec:	  Callstack bug: 	 False
INFO:symExec:	  Concurrency bug: 	 False
INFO:symExec:	  Time dependency bug: 	 False
INFO:symExec:	  Reentrancy bug: 	 False
INFO:symExec:	 --- 50.0333039761 seconds ---
INFO:symExec:	====== Analysis Completed ======
INFO:root:Contract //root/smartbugs/dataset/int_bugs_9/0604/repair_cha/PYLNT_repair_mutation_for_greater_line_197.sol:SafeMath:
INFO:symExec:Running, please wait...
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 100.0%
INFO:symExec:	  Arithmetic bugs: 	 False
INFO:symExec:	  └> Overflow bugs: 	 False
INFO:symExec:	  └> Underflow bugs: 	 False
INFO:symExec:	  └> Division bugs: 	 False
INFO:symExec:	  └> Modulo bugs:   	 False
INFO:symExec:	  └> Truncation bugs: 	 False
INFO:symExec:	  └> Signedness bugs: 	 False
INFO:symExec:	  Callstack bug: 	 False
INFO:symExec:	  Concurrency bug: 	 False
INFO:symExec:	  Time dependency bug: 	 False
INFO:symExec:	  Reentrancy bug: 	 False
INFO:symExec:	 --- 0.0127129554749 seconds ---
INFO:symExec:	====== Analysis Completed ======
INFO:root:Contract //root/smartbugs/dataset/int_bugs_9/0604/repair_cha/PYLNT_repair_mutation_for_greater_line_197.sol:owned:
INFO:symExec:Running, please wait...
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 99.4%
INFO:symExec:	  Arithmetic bugs: 	 False
INFO:symExec:	  └> Overflow bugs: 	 False
INFO:symExec:	  └> Underflow bugs: 	 False
INFO:symExec:	  └> Division bugs: 	 False
INFO:symExec:	  └> Modulo bugs:   	 False
INFO:symExec:	  └> Truncation bugs: 	 False
INFO:symExec:	  └> Signedness bugs: 	 False
INFO:symExec:	  Callstack bug: 	 False
INFO:symExec:	  Concurrency bug: 	 False
INFO:symExec:	  Time dependency bug: 	 False
INFO:symExec:	  Reentrancy bug: 	 False
INFO:symExec:	 --- 0.243875980377 seconds ---
INFO:symExec:	====== Analysis Completed ======
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored