INFO:root:Contract //root/smartbugs/dataset/int_bugs_9/0604/repair_tru/BCDN_repair_mutation_for_inttruncate_175_1.sol:blockcdn:
INFO:symExec:Running, please wait...
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 418, in propagate_taint
    if arithmetic_error["instruction"].data_in[0] == 32 or arithmetic_error["instruction"].data_in[0] == 31:
  File "/root/osiris/z3/z3.py", line 302, in __nonzero__
    return self.__bool__()
  File "/root/osiris/z3/z3.py", line 305, in __bool__
    if is_true(self):
  File "/root/osiris/z3/z3.py", line 1367, in is_true
    return is_app_of(a, Z3_OP_TRUE)
  File "/root/osiris/z3/z3.py", line 1164, in is_app_of
    return is_app(a) and a.decl().kind() == k
  File "/root/osiris/z3/z3.py", line 885, in decl
    return FuncDeclRef(Z3_get_app_decl(self.ctx_ref(), self.as_ast()), self.ctx)
  File "/root/osiris/z3/z3.py", line 801, in as_ast
    def as_ast(self):
  File "/root/osiris/symExec.py", line 2868, in handler
    raise Exception("timeout")
Exception: timeout
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 65.9%
INFO:symExec:	  Arithmetic bugs: 	 True
INFO:symExec:	  └> Overflow bugs: 	 True
//root/smartbugs/dataset/int_bugs_9/0604/repair_tru/BCDN_repair_mutation_for_inttruncate_175_1.sol:blockcdn:173:9
totalSupply +=  halfValue
^
INFO:symExec:	  └> Underflow bugs: 	 False
INFO:symExec:	  └> Division bugs: 	 False
INFO:symExec:	  └> Modulo bugs:   	 False
INFO:symExec:	  └> Truncation bugs: 	 False
INFO:symExec:	  └> Signedness bugs: 	 False
INFO:symExec:	  Callstack bug: 	 False
INFO:symExec:	  Concurrency bug: 	 True
Flow 1:
//root/smartbugs/dataset/int_bugs_9/0604/repair_tru/BCDN_repair_mutation_for_inttruncate_175_1.sol:blockcdn:111:13
msg.sender.send(value)
^
Flow 2:
//root/smartbugs/dataset/int_bugs_9/0604/repair_tru/BCDN_repair_mutation_for_inttruncate_175_1.sol:blockcdn:196:13
msg.sender.send(value)
^
INFO:symExec:	  Time dependency bug: 	 True
//root/smartbugs/dataset/int_bugs_9/0604/repair_tru/BCDN_repair_mutation_for_inttruncate_175_1.sol:blockcdn:192:9
if(now <= closeTime ) throw
^
//root/smartbugs/dataset/int_bugs_9/0604/repair_tru/BCDN_repair_mutation_for_inttruncate_175_1.sol:blockcdn:106:9
if(now <= closeTime) throw
^
INFO:symExec:	  Reentrancy bug: 	 False
INFO:symExec:	 --- 50.0972709656 seconds ---
INFO:symExec:	====== Analysis Completed ======

  .oooooo.             o8o            o8o          
 d8P'  `Y8b            `"'            `"'          
888      888  .oooo.o oooo  oooo d8b oooo   .oooo.o
888      888 d88(  "8 `888  `888""8P `888  d88(  "8
888      888 `"Y88b.   888   888      888  `"Y88b. 
`88b    d88' o.  )88b  888   888      888  o.  )88b
 `Y8bood8P'  8""888P' o888o d888b    o888o 8""888P'


!!! SYMBOLIC EXECUTION TIMEOUT !!!
Unexpected error: <type 'exceptions.Exception'>